### ISSUE TITLE
verifier que les donnees geo de Thomas match les donnees de l'equipe data

### ISSUE THREAD

**Issue by demondragong** [dataforgoodfr/batch8_mednum#20]

**Comment by slamer59** [comment]
Les données que j'utilise sont celles définies ici:
https://github.com/dataforgoodfr/batch8_mednum/blob/2938c583dabe91288053715c7ce0fc34d491715c/mednum/config/__init__.py#L19

2017. Me dire quoi prendre sinon. Quelle source de données d'entrées ? Je n'ai pas vu de soucis "a la grosse". Le plus simple est que vous me donniez sur quoi vous vous basé. Un merge sera fait entre les paramètres et les données géographiques. 

Si il s'agit d'un lien, il faut juste changer le lien dans le fichier précédent.

**Comment by slamer59** [comment]
A priori, on peut fermer ce point.
