### ISSUE TITLE
[LANDING et DASHBOARD] incorporer changements graphiques selon nouveau proto figma :

### ISSUE THREAD

**Issue by demondragong** [dataforgoodfr/batch8_mednum#25]

**Comment by slamer59** [comment]
@demondragong Peux-tu faire une petite liste des changements souhaités ? J'ai fait yune première PR pour avancer dessus.

**Comment by demondragong** [comment]
- [ ] intégrer le menu et le style de la landing sur le dashboard une fois html et css fourni par presta
- [x] sur la carte : enlever les graduations et mentions "latitude"et "longitude" à gauche et en bas
- [x] retirer placeholders "Score Global | 0->250" et "Population | 1055000"
- [x] dans le bandeau du haute, remplacer "Un score de 100 correspond à la moyenne de référence pour un territoire sur un axe de fragilité." par "Un score supérieur à 100 indique une fragilité. Plus le score est élevé, plus le risque d'exclusion numérique est important."

voilà un premier jet :) @slamer59

**Comment by demondragong** [comment]
@outinim work in progress :)

**Comment by slamer59** [comment]
Suppression d'une partie du style dans **reset.css**
Cela "casse" l'application. Noter l'absence des boutons.


![image](https://user-images.githubusercontent.com/25283272/102123983-fb9e7c80-3e47-11eb-92e9-f0a27b758f62.png)

_input,
textarea {
    -webkit-appearance: none;
    -ms-appearance: none;
    appearance: none;
    -moz-appearance: none;
    -o-appearance: none;
    border-radius: 0;
}_

**Comment by slamer59** [comment]
**reset.css**
Forcé à une taille plus petite

#header {
    width: 100%;
    position: relative;
    height: 150px;
    background-color: #FFF6F6
}
